kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      # application
      - containerPort: 8443
        hostPort: 443
      # kubernetes-dashboard
      - containerPort: 30080
        hostPort: 30080