# https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax

# Continuous Integration (CI) workflow for Pull Requests (PRs) and pushes to main branch.
name: Build

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  packages: write

jobs:
  ci:
    name: Lint, Format, Unit Test, Build, Coverage, Release Snapshot
    runs-on: ubuntu-latest
    steps:

      - name: Setup / Check out code into the Go module directory
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          fetch-depth: 0

      - name: Setup / pnpm for frontend build
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4
        with:
          version: 10
          run_install: false

      - name: Setup / Install frontend dependencies
        run: pnpm install
        working-directory: ./api/frontend

      - name: Setup / Go
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version: 1.25.5

      - name: Run / Make CI
        run: make ci

      - name: Test / Upload coverage to Codecov
        uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7 # v5.5.1
        # Skip Codecov for Dependabot PRs
        if: ${{ !startsWith(github.head_ref, 'dependabot/') }}
        with:
          fail_ci_if_error: true
          files: .coverage/coverage.filtered.out, api/frontend/coverage/coverage-final.json
          slug: cooperlutz/go-full
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Run / GoReleaser
        uses: goreleaser/goreleaser-action@e435ccd777264be153ace6237001ef4d979d3a7a # v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run / End to End Tests
        run: make compose-e2e

      - name: Publish / Upload dist
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          path: dist
          retention-days: 1